### ISSUE TITLE
17.) As a doer, I can set a habit event to have an optional photograph so I can record what happened.

### ISSUE THREAD

**Issue by thecatinbox** [CMPUT301F21T01/HabitUp#16]
17.) As a doer, I can set a habit event to have an optional photograph so I can record what happened.
Story Points: 3
Risk: Low

**Comment by thecatinbox** [comment]
Done Oct 25th 2021: 544ca00c11bf172c667e891da7ba5d7694926d9f

**Comment by SashaDmytryshyn** [comment]
Need to add functionality to store and read Image from firebase

**Comment by thecatinbox** [comment]
store and read Image from firebase done ff204d1fc0033494484f3cf8dbd11f516b326d6b
