### ISSUE TITLE
7.) As a doer, I can add a habit event when a habit is complete.

### ISSUE THREAD

**Issue by thecatinbox** [CMPUT301F21T01/HabitUp#17]
7.) As a doer, I can add a habit event when a habit is complete.
Story Points: 1
Risk: High

**Comment by thecatinbox** [comment]
Patially done Oct 25th 2021: 544ca00c11bf172c667e891da7ba5d7694926d9f
Todo: need to add a habit event only when a habit is complete, now the user can add a habit event anytime as they wish

**Comment by thecatinbox** [comment]
Need test cases

**Comment by SashaDmytryshyn** [comment]
test cases done in e58631d9cbd0fa8b58d420bed1260c84bd8f35b4
