### ISSUE TITLE
2.) As a doer, I can view a habit and it's details.

### ISSUE THREAD

**Issue by mattypaez** [CMPUT301F21T01/HabitUp#19]
Story Points: 1
Risk: high

**Comment by mattypaez** [comment]
I completed and fixed this issue in: ee5632d7a3b7dbe5eb25ecb1b58a7ceaa4e19434

**Comment by twrkonrad** [comment]
uses implementation from: e37ffed2ac7e26f524898e9897f458469c30d2c2
