### ISSUE TITLE
11.) As a doer, I can set a habit to have a day(s) of the week on which it occurs.

### ISSUE THREAD

**Issue by mattypaez** [CMPUT301F21T01/HabitUp#20]
Story Points: 2
Risk: Medium

**Comment by mattypaez** [comment]
this was completed and fixed in: fc4fd55a1a5472beed18cca020d248f8833c7ead

**Comment by twrkonrad** [comment]
added initialization of checkboxes for existing habits here: e37ffed2ac7e26f524898e9897f458469c30d2c2
