### ISSUE TITLE
1.) As a doer, I can add habits, give them a title, a starting date, and a reason.

### ISSUE THREAD

**Issue by twrkonrad** [CMPUT301F21T01/HabitUp#29]
Story Points: 1
Risk: High

**Comment by twrkonrad** [comment]
added base code in this commit: 13da2d85fa4d8e30d055cfb91261004a1bd83cda

**Comment by mattypaez** [comment]
this was completed and fixed in: 540b63c95c8f827086b04f199ebb99284685ab07
