### ISSUE TITLE
12.) As a doer, I want for each habit on the list, a visual indicator to show how closely I am following its plan over time.

### ISSUE THREAD

**Issue by twrkonrad** [CMPUT301F21T01/HabitUp#33]
Story Points: 2
Risk: Medium

**Comment by twrkonrad** [comment]
first initialized here: 2e34377ce42b00adb54d6e836a5a66632bccb5ff
xml layout from: @SashaDmytryshyn

**Comment by mattypaez** [comment]
added progress bar when viewing a habit in: ee5632d7a3b7dbe5eb25ecb1b58a7ceaa4e19434

**Comment by twrkonrad** [comment]
resolved here: 2e34377ce42b00adb54d6e836a5a66632bccb5ff

**Comment by mattypaez** [comment]
progress is a fixed number upon initial adding/editing of a habit and doesn't update any other time, need to fix!

**Comment by mattypaez** [comment]
the progress is fixed and this issue is completed in: ae3f46353f0a7cd95fdc483479f2c21e20ca9667
