### ISSUE TITLE
9.) As a doer, I can delete a habit event.

### ISSUE THREAD

**Issue by SashaDmytryshyn** [CMPUT301F21T01/HabitUp#35]
Story Points: 1
Risk: High

**Comment by SashaDmytryshyn** [comment]
Finished, making sure it passes tests

**Comment by SashaDmytryshyn** [comment]
Works successfully. Test not currently made for it but it works. Will create later issue for test, but closing this one for functionality.

**Comment by thecatinbox** [comment]
Need test cases

**Comment by SashaDmytryshyn** [comment]
test cases done in e6974285aee1d29ed8feda46a4d02b7712f34369
