### ISSUE TITLE
10.) As a doer, I can edit a habit event.

### ISSUE THREAD

**Issue by thecatinbox** [CMPUT301F21T01/HabitUp#36]
Story Points: 1
Risk: High

**Comment by thecatinbox** [comment]
Partially done Nov 3rd 2021: c25b5b1f1eb61d6371896befbb2a1f915ddd5f76
Problem: can only edit habit event by clicking the first button in the list

**Comment by thecatinbox** [comment]
Now click on the Habit Event Item allows you to edit it. Will reopen this issue if need further update.  a3406cb6ac449d66e0d94d21ba03de05c1a942d5

**Comment by thecatinbox** [comment]
Update: now the edit button is inside the ViewHabitEventActivity 212e582e3fc76ae5c662d37dced64953adee436a

**Comment by SashaDmytryshyn** [comment]
need to add with firebase functionality

**Comment by thecatinbox** [comment]
Done connecting to database: e3aeff8801f5d431a7ab74edea977feb5d1d6999

**Comment by thecatinbox** [comment]
Need test cases

**Comment by thecatinbox** [comment]
test cases done 0718920cf535c9791da65abb9d4e51f6897665d1
