### ISSUE TITLE
Document certain parts of code

### ISSUE THREAD

**Issue by kos-maj** [CMPUT301F21T01/HabitUp#66]
Project Part 3 Feedback

- "Some portions of code seem inconsistently documented. For example, some classes have parameters with no explanation for their usage on some methods."

**Comment by kos-maj** [comment]
Added some missing JavaDoc for Habit in ec7ded16cc9b88c601897887c8dc2b7db8e2d2e5

**Comment by mattypaez** [comment]
added and fixed javadoc for all habit related classes in fa788d6129177d31aa5995630991bab681f046d8

**Comment by kos-maj** [comment]
JavaDoc present for all classes/methods as of commit c8160e81f245b546b070b0721940797a55c834f4
