### ISSUE TITLE
UML Touch-up

### ISSUE THREAD

**Issue by kos-maj** [CMPUT301F21T01/HabitUp#67]
Project Part 3 Feedback

- "HabitEventActivity does not have EditHabitEventFragment. The class ViewHabitEventActivity has that fragment."
- UML diagram does not include ViewHabitEventActivity
- Difference between solid line association and dashed arrows. Do not confuse with inheritance (triangle arrow head)
- "AddPhotograh and AddLocation are activities. Would you like to rename them (add Activity to the end) so that users can quickly recognize those."
- "All fragments have the multiplicity 0..*. Does your app create more than 1 fragment (of given type)?"

**Comment by thecatinbox** [comment]
UML Updated: 
1. Attached EditHabitEventFragment to ViewHabitEventActivity  
2. Added ViewHabitEventActivity 
3. Still need to work on it
4. Changed names to AddPhotograhActivity and AddLocationActivity
5. All fragments now have multiplicity 0

**Comment by thecatinbox** [comment]
done https://lucid.app/lucidchart/8784f16e-ca86-40c9-8fd5-c3c198141c9d/edit?from_docslist=true&page=0_0&invitationId=inv_d347ef95-9f05-49c1-8f7b-4a030d6983da#
