### ISSUE TITLE
Fixing JavaDoc and comments for all habit event classes

### ISSUE THREAD

**Issue by thecatinbox** [CMPUT301F21T01/HabitUp#75]

**Comment by SashaDmytryshyn** [comment]
done most in dc5d2187f71d695abf5264a1b0fbfb6f2e841534

**Comment by SashaDmytryshyn** [comment]
more here cb5ca7d832bff29b335cdb685fa9f9dc563fa346

**Comment by thecatinbox** [comment]
add/edit fragments & add location/photograph a8a3d69463cfd3f17920e78b4585a146cd2213f1

**Comment by SashaDmytryshyn** [comment]
checked every class, tiny polishes c8160e81f245b546b070b0721940797a55c834f4

**Comment by SashaDmytryshyn** [comment]
and we are done c8160e81f245b546b070b0721940797a55c834f4
